<?php declare(strict_types=1);
namespace Backend\Core;
defined("ACCESS") or exit("Access Denied");

use Backend\Core\SiteMapper;
use Backend\Core\PHPJS;

class Router
{
    private array $registeredRoutes = [];
    private array $ignoreMaintenanceRoutes = array();
    private string $defaultRouteHandler = "";
    private string $lastRenderedTemplate = "";

    protected function handleRoutes(): void
    {
        // Parse route and variables from url
        $urlRequest = $this->getURLRequest();
        $route = $urlRequest["route"];
        $variables = $urlRequest["variables"];

        // Display maintenance if needed
        if (MAINTENANCE_MODE)
        {
            $ignoreMaintenance = in_array($route, $this->ignoreMaintenanceRoutes, true);

            if (!$ignoreMaintenance && !Session::has("maintenance_access_granted"))
            {
                $this->renderMaintenancePage();
            }
        }

        // Set handler method call
        $requestedMethod = isset($this->registeredRoutes[$route]) ? [$this, $this->registeredRoutes[$route]] :  [$this, $this->defaultRouteHandler];
        if (!method_exists($this, $requestedMethod[1]))
        {
            kristal_fatalExit("Route does not have a handler named '{$requestedMethod[1]}' or it's not available.");
        }

        // Call the correct route
        $this->{$requestedMethod[1]}(...$variables);

        // Build sitemap
        if (AUTO_COMPILE_SITEMAP && !Session::get("logged_in"))
            new SiteMapper($this->registeredRoutes, $route, $this->lastRenderedTemplate);
    }

    protected function addRoute(string $routeName, string $handler): void
    {
        $routeName = trim($routeName, "/") . "/";
        $this->registeredRoutes[$routeName] = $handler;
    }

    protected function setDefaultHandler(string $handler): void
    {
        $this->defaultRouteHandler = $handler;
    }

    protected function setHomepageHandler(string $handler): void
    {
        $this->registeredRoutes[""] = $handler;

        if (ENABLE_LANGUAGES)
        {
            foreach (AVAILABLE_LANGUAGES as $language)
            {
                $this->registeredRoutes[$language . "/"] = $handler;
            }
        }
    }

    protected function ignoreMaintenance(array $routes): void
    {
        foreach ($routes as $route)
        {
            $this->ignoreMaintenanceRoutes[] = $route;
        }
    }

    private function getURLRequest(): array
    {
        // Parse page name and variables from the URL
        $url = parse_url($_SERVER["REQUEST_URI"], PHP_URL_PATH);
        $params = array_filter(explode("/", $url));
        $params = array_values($params);
        
        // Handle multilingual support
        if (ENABLE_LANGUAGES)
        {
            // Get language and page from URL parameters
            $language = isset($params[0]) ? strtolower($params[0]) : "";
            $route = isset($params[1]) ? strtolower($params[1]) : "";

            // Redirect to default language home page if language was not valid
            if (!in_array($language, array_map('strtolower', AVAILABLE_LANGUAGES)))
            {
                setAppLocale(DEFAULT_LANGUAGE);
                redirect(route(""));
            }

            $route = $language . "/" . $route;
            unset($params[0], $params[1]);
            setAppLocale($language);
        }
        else
        {
            $route = isset($params[0]) ? strtolower($params[0]) : "";
            unset($params[0]);
        }

        // Make sure page ends with "/"
        $route = trim($route, "/") . "/";

        // Set "" and "/" to be the same
        if ($route === "/")
        {
            $route = "";
        }
        
        return ['route' => $route, 'variables' => array_values($params)];
    }

    protected function render(string $page, array $variables = []): void
    {
        // Make sure only one view can be called
        if (!empty($this->lastRenderedTemplate))
        {
            if (!PRODUCTION_MODE)
            {
                debug("Multiple render() calls are not supported, cancelling second render call.");
            }
            return;
        }

        echo "<!-- Page Generated by Kristal Framework -->\n";

        // Include variables passed by the route function
        foreach ($variables as $key => $value)
        {
            if (is_string($key))
            {
                $$key = $value;
            }
        }

        // Include metadata from config.php
        $kristal_metadata = METADATA;

        // Include header
        if (!file_exists(page("base/header.php")))
        {
            kristal_fatalExit("Route: '" . $page . "' has handler '" . $page . ", but this handler function is not available.");
        }
        include_once page("base/header.php");

        // Make sure page is a php file
        $page = ensurePHPExtension($page);

        // Include the requested page
        if (!file_exists(page($page)))
        {
            kristal_fatalExit("Tried to render page: " . $page . ", but template was not found at " . page($page) . ".");
        }
        else
        {
            include_once page($page);
        }

        // Render PHP created javascript variables and code
        PHPJS::release();

        // Render footer
        if (!file_exists(page("base/footer.php")))
        {
            kristal_fatalExit("Failed to build, " . page("base/footer.php") . " was not found.");
        }
        else
        {
            include_once page("base/footer.php");
        }
        
        $this->lastRenderedTemplate = $page;
        
    }

    private function renderMaintenancePage(): void
    {
        if (Session::has("maintenance_access_granted"))
            return;

        if (ENABLE_MAINTENANCE_LOGIN)
        {
            $authenticationFailed = false;
            $authenticationAttemptLimitReached = false;
            $authenticationLockoutLabel = "";
            $loginAttempts = Session::get("maintenance_login_attempts", 1);
            $lockoutStartedAt = Session::get("maintenance_lockout_started_at", null);
    
            // Check have we reached login attempt count
            if ($loginAttempts >= MAINTENANCE_LOCKOUT_LIMIT)
            {
                $authenticationAttemptLimitReached = true;
    
                if ($lockoutStartedAt === null)
                {
                    $lockoutStartedAt = time();
                    Session::add("maintenance_lockout_started_at", $lockoutStartedAt);
                }
            }
    
            // Handle lockout countdown
            if ($authenticationAttemptLimitReached)
            {
                $remainingLockoutSeconds = MAINTENANCE_LOCKOUT_CLEAR_TIME - (time() - $lockoutStartedAt);
        
                if ($remainingLockoutSeconds > 0)
                {
                    if ($remainingLockoutSeconds > 60)
                    {
                        $authenticationLockoutLabel = floor($remainingLockoutSeconds / 60) . " min";
                    }
                    else
                    {
                        $authenticationLockoutLabel = $remainingLockoutSeconds . " s";
                    }
                }
                else
                {
                    $loginAttempts = 0;
                    $authenticationAttemptLimitReached = false;
                    Session::remove("maintenance_failed_attempts");
                    Session::remove("maintenance_lockout_started_at");
                }
            }
    
            // Handle authentication request
            if (!$authenticationAttemptLimitReached && $_SERVER["REQUEST_METHOD"] === "POST" && isset($_POST["maintenance-password"]))
            {
                if ($_POST["maintenance-password"] === MAINTENANCE_PASSWORD)
                {
                    Session::add("maintenance_access_granted", "Granted");
                    return;
                }
                else
                {
                    $authenticationFailed = true;
                    $loginAttempts++;
                    Session::add("maintenance_login_attempts", $loginAttempts);
                }
            }
        }
        
        // Render maintenance page
        $maintenancePagePath = PATH_TEMPLATES . "maintenance.php";
    
        if (!file_exists($maintenancePagePath))
        {
            kristal_fatalExit("Maintenance page is missing. It should be located at " . $maintenancePagePath, "Site is under maintenance");
        }

        include $maintenancePagePath;
        PHPJS::release();
        exit;
    }
}
