$(document).ready(function(){$("body").addClass("signup-gradient");$("#terms-of-service-link").on("click",function(){$("#terms-of-service-popup").fadeIn(150).css("display","flex");});$("#tos-agree-button").on("click",function(){$("#terms-of-service-checkbox").prop("checked",true);$("#terms-of-service-popup").fadeOut(150);validateSignupForm();});$("#tos-disagree-button").on("click",function(){$("#terms-of-service-checkbox").prop("checked",false);$("#terms-of-service-popup").fadeOut(150);validateSignupForm();});$("#registration-username, #registration-email, #registration-password, #registration-confirmation-password, #terms-of-service-checkbox").on("input change",function(){validateSignupForm();});if($("#registration-feedback").text()===""){validateSignupForm();}});function validateSignupForm(){const username=$("#registration-username").val().trim();const email=$("#registration-email").val().trim().toLowerCase();const password=$("#registration-password").val();const confirmPassword=$("#registration-confirmation-password").val();const termsChecked=$("#terms-of-service-checkbox").is(":checked");const feedback=$("#registration-feedback");const button=$("#registration-button");feedback.removeClass("failed warning info success");feedback.text("");if(username.length<3){feedback.addClass("failed").text("Please enter a username (minimum 3 characters).");button.prop("disabled",true);return;}
if(username.length>50){feedback.addClass("failed").text("Username has to be shorter than 50 characters.");button.prop("disabled",true);return;}
if(!/^[A-Za-z0-9_-]+$/.test(username)){feedback.addClass("failed").text("Username may only contain letters, numbers, underscores, and hyphens.");button.prop("disabled",true);return;}
if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){feedback.addClass("failed").text("Please enter a valid email address.");button.prop("disabled",true);return;}
if(password.length<8){feedback.addClass("failed").text("Password must be at least 8 characters long.");button.prop("disabled",true);return;}
if(password!==confirmPassword){feedback.addClass("failed").text("Confirmation password does not match.");button.prop("disabled",true);return;}
if(!termsChecked){feedback.addClass("failed").text("Please accept the Terms of Service.");button.prop("disabled",true);return;}
if(isWeakPassword(password)){feedback.addClass("warning").text("Your password is quite weak. We strongly recommend choosing a stronger one.");}
button.prop("disabled",false);}
function isWeakPassword(password){let score=0;if(password.length>=8)score++;if(password.length>=12)score++;if(password.length>=16)score++;if(/[a-z]/.test(password))score++;if(/[A-Z]/.test(password))score++;if(/\d/.test(password))score++;if(/[^A-Za-z0-9]/.test(password))score++;const uniqueCount=new Set(password).size;if(uniqueCount>=6)score++;if(uniqueCount>=10)score++;return score<5;}
/* Generated: 14.12.2025 11:56:30 */
//# sourceMappingURL=create-account.js.map
